BOT_NAME = "Pasadóir"
BOT_NICK = "pasadoir"

LOOKBACK_LENGTH = 2
CACHE_CAPACITY = 12
CACHE_MIN_LOOKBACKS = 5000

SOURCE_EXTENSION = ".src"
MERGE_INFO_FILENAME = "merge.lst"
SOURCE_INFO_FILENAME = "source.info"
SOURCE_INFO_KEY_DATE = "date"
SOURCE_INFO_KEY_CHANNELS = "channels"

GENERATE_REQUEST_TRIGGER = "!"
GENERATE_FORWARD_REQUEST_TRIGGER = "^"
GENERATE_REVERSE_REQUEST_TRIGGER = "~"
META_REQUEST_TRIGGER = "@"

STATS_SPEAKER_ALIAS_COUNT = 3 # This must be greater than or equal to 2
